name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main # Change this to your 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USER }}/my-workout-app:latest .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_PASSWORD }}/my-workout-app:latest


# name: Google Cloud Engine Deployment

# on:
#   push:
#     branches:
#       - main  # Adjust branch name as needed

# jobs:
#   deploy:
#     name: Deploy to Google Cloud Engine
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Google Cloud SDK
#         uses: zxyle/publish-gae-action@master
#         with:
#           project_id: ${{ secrets.PROJECT_ID }}
#           service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
#           service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}     


#       - uses: 'actions/checkout@v4' # Must come first!
#       - uses: 'google-github-actions/auth@v2'
#         with:
#           credentials_json: ${{ secrets.credentials_json }}

#       - name: Initialize App Engine application
#         run: |
#           gcloud app describe || gcloud app create --region=us-east1  
            
#       - name: Build and deploy frontend (React.js)
#         run: |
#           npm install
#           npm run build
#           gcloud app deploy app.yaml --quiet



          



