name: Google Cloud Engine Deployment

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  deploy:
    name: Deploy to Google Cloud Engine
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: zxyle/publish-gae-action@master
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}     

  # authenticate:
  #   name: Authenticate to Google Cloud
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

      - uses: 'actions/checkout@v4' # Must come first!
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.credentials_json }}

      - name: Initialize App Engine application
        run: |
          gcloud app describe || gcloud app create --region=us-east1  
            
      - name: Build and deploy frontend (React.js)
        run: |
          npm install
          npm run build
          gcloud app deploy app.yaml --quiet

      ## - name: Generate commit SHA
      #   id: commit_sha
      #   run: echo "::set-output name=sha::$(git rev-parse HEAD)"

      # - name: SonarQube Analysis
      #   uses: sonarsource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # - name: Rollback on failure
      #   if: ${{ failure() }}
      #   run: |
      #     echo "Deployment failed. Rolling back to previous commit."
      #     git revert ${{ steps.commit_sha.outputs.sha }}
      #     git push origin main



